AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*.rb'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/LineLength:
  IgnoredPatterns: ['\A\s*#']

Style/Documentation:
  Enabled: false
