AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/graphql/**/*'

Metrics/LineLength:
  IgnoredPatterns: ['\A\s*#']

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false
