FACEBOOK_KEY: '130521764236100'
FACEBOOK_SECRET: 'ddb4113835f442eb4f185e7d274e3102'
GOOGLE_KEY: '1055962248659-absiprapnnrlut42fe5ktnqsgaucb9ln.apps.googleusercontent.com'
GOOGLE_SECRET: 'OvzFLvffHM63MCY5VHNPBndI'
TWITTER_KEY: 'TmL1MeTs77ubAJqg37yzpjmRZ'
TWITTER_SECRET: 'N78l1vxqIcY7H9K1zBxkFOAQhOJnBIjGOn1WxXhNLmxk8e964K'
